In [1]:
import math
from datetime import datetime
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
import mysql.connector

In [2]:
#df = pd.read_csv('BC-climate-monthly.csv')
#df = pd.read_csv('AB-climate-monthly.csv')
df = pd.read_csv('SK-climate-monthly.csv')
#df = pd.read_csv('MB-climate-monthly.csv')
#df = pd.read_csv('ON-climate-monthly.csv')
#df = pd.read_csv('QC-climate-monthly.csv')
#df = pd.read_csv('NB-climate-monthly.csv')
#df = pd.read_csv('NS-climate-monthly.csv')
#df = pd.read_csv('NL-climate-monthly.csv')
#df = pd.read_csv('PE-climate-monthly.csv')

In [3]:
df

,x,y,LATITUDE,LONGITUDE,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,LAST_UPDATED,PROVINCE_CODE,...,DAYS_WITH_PRECIP_GE_1MM,NORMAL_SNOWFALL,TOTAL_SNOWFALL,DAYS_WITH_VALID_SNOWFALL,SNOW_ON_GROUND_LAST_DAY,NORMAL_SUNSHINE,BRIGHT_SUNSHINE,DAYS_WITH_VALID_SUNSHINE,COOLING_DEGREE_DAYS,HEATING_DEGREE_DAYS
0,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.1,2000-01,2014-07-31 11:50:00,SK,...,4.0,NaN,25.2,31.0,NaN,NaN,NaN,NaN,NaN,NaN
1,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.2,2000-02,2014-07-31 11:50:00,SK,...,2.0,NaN,18.2,29.0,0.0,NaN,NaN,NaN,NaN,NaN
2,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.10,2001-10,2014-07-31 11:50:00,SK,...,1.0,NaN,1.0,31.0,0.0,NaN,NaN,NaN,NaN,NaN
3,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.11,2001-11,2014-07-31 11:50:00,SK,...,2.0,NaN,1.0,30.0,0.0,NaN,NaN,NaN,NaN,NaN
4,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.12,2001-12,2014-07-31 11:50:00,SK,...,0.0,NaN,0.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26424,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.10,2018-10,2018-12-06 09:47:13,SK,...,4.0,8.05,10.4,27.0,0.0,NaN,NaN,NaN,0.0,431.6
26425,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.11,2018-11,2018-12-31 14:49:21,SK,...,7.0,22.16,15.0,25.0,0.0,NaN,NaN,NaN,0.0,664.5
26426,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.12,2018-12,2019-05-16 09:47:16,SK,...,9.0,27.22,17.8,26.0,22.0,NaN,NaN,NaN,0.0,773.5
26427,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.1,2019-01,2019-05-16 09:48:50,SK,...,2.0,22.31,15.0,11.0,NaN,NaN,NaN,NaN,0.0,337.5
26428,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.3,2019-03,2019-05-16 09:48:50,SK,...,0.0,19.93,1.0,25.0,21.0,NaN,NaN,NaN,0.0,549.6

In [4]:
df.columns

Index(['x', 'y', 'LATITUDE', 'LONGITUDE', 'STATION_NAME', 'CLIMATE_IDENTIFIER',
       'ID', 'LOCAL_DATE', 'LAST_UPDATED', 'PROVINCE_CODE',
       'ENG_PROVINCE_NAME', 'FRE_PROVINCE_NAME', 'LOCAL_YEAR', 'LOCAL_MONTH',
       'NORMAL_MEAN_TEMPERATURE', 'MEAN_TEMPERATURE',
       'DAYS_WITH_VALID_MEAN_TEMP', 'MIN_TEMPERATURE',
       'DAYS_WITH_VALID_MIN_TEMP', 'MAX_TEMPERATURE',
       'DAYS_WITH_VALID_MAX_TEMP', 'NORMAL_PRECIPITATION',
       'TOTAL_PRECIPITATION', 'DAYS_WITH_VALID_PRECIP',
       'DAYS_WITH_PRECIP_GE_1MM', 'NORMAL_SNOWFALL', 'TOTAL_SNOWFALL',
       'DAYS_WITH_VALID_SNOWFALL', 'SNOW_ON_GROUND_LAST_DAY',
       'NORMAL_SUNSHINE', 'BRIGHT_SUNSHINE', 'DAYS_WITH_VALID_SUNSHINE',
       'COOLING_DEGREE_DAYS', 'HEATING_DEGREE_DAYS'],
      dtype='object')

In [5]:
df[['CLIMATE_IDENTIFIER', 'LOCAL_YEAR', 'LOCAL_MONTH', 'MEAN_TEMPERATURE', 'MIN_TEMPERATURE', 'MAX_TEMPERATURE', \
   'TOTAL_PRECIPITATION', 'STATION_NAME']]

,CLIMATE_IDENTIFIER,LOCAL_YEAR,LOCAL_MONTH,MEAN_TEMPERATURE,MIN_TEMPERATURE,MAX_TEMPERATURE,TOTAL_PRECIPITATION,STATION_NAME
0,4010100,2000,1,NaN,NaN,NaN,25.2,ALIDA
1,4010100,2000,2,NaN,NaN,NaN,18.2,ALIDA
2,4010100,2001,10,NaN,NaN,NaN,1.0,ALIDA
3,4010100,2001,11,NaN,NaN,NaN,2.0,ALIDA
4,4010100,2001,12,NaN,NaN,NaN,0.0,ALIDA
...,...,...,...,...,...,...,...,...
26424,4086001,2018,10,2.014815,-9.0,18.0,12.6,PELLY 2
26425,4086001,2018,11,-8.580000,-25.0,4.0,17.2,PELLY 2
26426,4086001,2018,12,-11.750000,-34.0,1.0,17.8,PELLY 2
26427,4086001,2019,1,-12.681818,-27.0,-1.0,15.0,PELLY 2
26428,4086001,2019,3,-3.984000,-27.5,9.5,1.3,PELLY 2

In [6]:
import requests
import time

In [7]:
df_clid = df[['CLIMATE_IDENTIFIER', 'LATITUDE', 'LONGITUDE']].copy()
df_clid = df_clid.groupby(['CLIMATE_IDENTIFIER']).max()
df_clid.reset_index(inplace = True)
print(df_clid)

    CLIMATE_IDENTIFIER  LATITUDE  LONGITUDE
0              4010100    49.450   -101.800
1              4010150    49.617   -104.733
2              4010310    50.817   -102.217
3              4010395    50.783   -103.617
4              4010400    50.900   -102.283
5              4010570    49.450   -102.983
6              4010811    50.201   -104.710
7              4010879    50.368   -102.571
8              4010984    50.550   -105.383
9              4011250    49.217   -101.750
10             4011441    49.383   -104.650
11             4011846    51.517   -101.783
12             4011980    50.850   -104.267
13             4012050    49.733   -105.033
14             4012120    51.267   -105.983
15             4012130    51.417   -105.800
16             4012381    51.800   -104.850
17             4012401    49.210   -102.966
18             4012403    49.210   -102.966
19             4012410    49.217   -102.967
20             4012483    51.150   -103.067
21             4012485    49.339   -101.448
22             4012943    51.500   -102.667
23             4012988    50.700   -102.633
24             4013098    49.833   -102.867
25             4013270    51.000   -105.517
26             4013401    52.267   -105.117
27             4013480    50.550   -103.650
28             4014138    49.067   -104.250
29             4014143    50.153   -102.394
30             4014145    50.900   -101.717
31             4014156    51.417   -105.250
32             4014322    52.000   -104.633
33             4014480    50.850   -103.767
34             4014481    51.152   -103.889
35             4014870    49.233   -103.233
36             4014913    49.617   -102.100
37             4015020    51.833   -103.333
38             4015045    49.833   -101.517
39             4015159    49.383   -103.300
40             4015258    50.250   -103.467
41             4015322    50.332   -105.538
42             4015328    50.341   -105.551
43             4015360    50.133   -101.667
44             4015560    51.517   -105.000
45             4015580    51.867   -102.067
46             4015800    49.317   -102.117
47             4015867    50.467   -106.067
48             4015870    51.403   -103.265
49             4015960    51.983   -103.917
50             4016322    50.567   -103.983
51             4016335    51.350   -104.417
52             4016521    49.600   -101.717
53             4016562    50.486   -104.586
54             4016563    50.408   -104.582
55             4016565    50.451   -104.667
56             4016566    50.432   -104.666
57             4016570    50.432   -104.666
58             4016651    50.567   -104.833
59             4016699    50.433   -104.667
60             4017095    50.967   -102.267
61             4017370    51.167   -104.400
62             4018508    50.450   -101.933
63             4018511    50.200   -101.983
64             4018642    51.667   -105.400
65             4018960    49.417   -102.500
66             4019035    51.767   -104.200
67             4019040    49.817   -104.183
68             4019041    49.817   -104.183
69             4019073    51.265   -102.464
70             4019075    51.265   -102.462
71             4019080    51.267   -102.467
72             4019082    51.200   -102.233
73             4019085    51.267   -102.462
74             4019095    51.214   -102.464
75             40190LN    51.767   -104.200
76             401FFDB    50.417   -104.583
77             401HP5R    49.700   -103.800
78             401I010    50.383   -102.683
79             401JR89    51.289   -106.848
80             401R001    50.433   -104.667
81             4020020    50.700   -108.783
82             4020160    49.717   -107.300
83             4020286    49.733   -105.933
84             4021996    49.667   -109.467
85             4022328    50.283   -106.183
86             4022359    51.133   -106.583
87             4022363    51.167   -106.550
88             4022368    51.133   -108.033
89             4022936    50.183   -109.800
90             4023212    50.467   -107.267
91             4023240    50.979   -107.935
92             4023800    49.667   -107.000
93             4024714    50.950   -107.150
94             4024919    49.903   -109.466
95             4026175    50.883   -109.050
96             4027485    49.650   -108.417
97             4027486    49.900   -108.417
98             4027775    50.600   -107.800
99             4028038    50.292   -107.691
100            4028040    50.300   -107.683
101            4028060    50.267   -107.733
102            4028101    50.050   -108.800
103            4029030    49.567   -106.783
104            402DAF0    50.909   -109.500
105            4031585    49.200   -108.383
106            40318MN    49.050   -105.483
107            4031999    49.650   -109.514
108            4032322    49.438   -108.983
109            4032766    49.200   -108.567
110            4034910    49.100   -107.017
111            4036844    49.168   -105.979
112            4038116    49.000   -108.383
113            4038400    49.370   -107.848
114            4038412    49.067   -107.583
115            4038740    49.000   -106.383
116            4040267    52.783   -109.900
117            4040430    52.773   -108.288
118            4040587    51.294   -108.407
119            4040600    52.067   -107.983
120            4043246    53.442   -109.723
121            4043750    51.972   -109.048
122            4043899    51.515   -109.181
123            4043900    51.517   -109.183
124            4043901    51.515   -109.181
125            4044152    53.033   -109.550
126            4044155    53.117   -109.633
127            4044850    52.333   -109.948
128            4045070    53.350   -108.033
129            4045605    52.767   -108.250
130            4045607    52.772   -108.256
131            4045695    52.769   -108.244
132            4046879    51.617   -108.017
133            4046884    51.567   -107.917
134            4046977    52.583   -107.850
135            4047238    52.383   -109.400
136            4047240    52.360   -108.835
137            4047241    52.360   -108.835
138            4047644    52.317   -107.767
139            4047681    51.517   -107.717
140            4048326    52.233   -109.200
141            4048521    53.131   -109.405
142            4050500    51.967   -106.700
143            4050774    52.550   -107.233
144            4051147    52.800   -106.567
145            4053120    51.733   -107.583
146            4053264    52.850   -105.783
147            4054795    53.017   -106.017
148            4055079    52.817   -104.600
149            4055165    51.433   -107.500
150            4055699    52.417   -106.500
151            4055736    51.483   -107.050
152            4056120    52.417   -105.150
153            4056121    52.417   -105.150
154            4056241    53.214   -105.673
155            4056243    53.210   -105.677
156            4056270    53.255   -105.549
157            4057122    52.104   -106.610
158            4057124    52.109   -106.705
159            4057152    52.171   -106.700
160            4057154    52.150   -106.550
161            4057155    52.150   -106.550
162            4057157    52.141   -106.624
163            4057165    52.174   -106.719
164            4057180    52.150   -106.600
165            4057202    52.117   -106.683
166            405DJDN    52.367   -107.017
167            4060452    54.335   -109.617
168            4060468    59.217   -109.700
169            4060982    55.833   -108.433
170            4060983    55.841   -108.421
171            4060988    55.842   -108.418
172            4061570    58.083   -104.483
173            4061592    58.391   -109.516
174            4061620    58.229   -103.678
175            4061629    58.229   -103.678
176            4061632    58.183   -103.700
177            4063560    55.533   -102.350
178            4063605    55.533   -102.350
179            4063623    54.908   -109.962
180            4063753    57.250   -105.600
181            4063755    57.250   -105.617
182            4063757    57.256   -105.618
183            4063759    57.250   -105.600
184            4064149    55.150   -105.267
185            4064155    55.151   -105.267
186            4064600    54.050   -109.100
187            4064620    54.020   -109.138
188            4065057    54.125   -108.050
189            4065058    54.133   -108.517
190            4065063    54.125   -108.523
191            4065710    55.650   -104.733
192            4067655    56.333   -103.283
193            4067723    53.367   -107.550
194            4067799    59.250   -105.841
195            4067PR5    59.250   -105.833
196            4068559    53.917   -106.067
197            4068840    56.233   -103.150
198            406N0NM    54.133   -108.517
199            406QLD0    59.567   -108.483
200            4070365    53.200   -103.800
201            4075518    53.333   -104.000
202            4075522    53.333   -104.017
203            4075525    53.333   -104.008
204            4077557    53.367   -103.167
205            4077605    53.583   -104.683
206            4078084    52.755   -103.400
207            407N51G    53.333   -104.000
208            4083322    52.817   -102.317
209            4083323    52.883   -102.583
210            4083324    52.817   -102.317
211            4085050    52.567   -103.833
212            4085052    52.583   -103.833
213            4086001    51.733   -101.900

In [8]:
def get_radiation_data(latitude, longitude):
    http_get = f'https://power.larc.nasa.gov/api/temporal/monthly/point?parameters=ALLSKY_SFC_PAR_TOT&community=AG&longitude={longitude}&latitude={latitude}&format=JSON&start=2000&end=2020'
    response = requests.get(http_get)
    return(response.json())

In [9]:
df_radiation = pd.DataFrame()

print('START: ' + str(datetime.now()))

for i in range(0, len(df_clid)):
    response = get_radiation_data(df_clid.iloc[i].LATITUDE, df_clid.iloc[i].LONGITUDE)
    time.sleep(2) #API limit is 60 requests per minute
    station = response['properties']['parameter']['ALLSKY_SFC_PAR_TOT']
    df_station = pd.DataFrame.from_dict(station, orient = 'index')
    df_station['climate_id'] = df_clid.iloc[i].CLIMATE_IDENTIFIER
    df_radiation = pd.concat([df_radiation, df_station], axis = 0)
    
print('FINISH: ' + str(datetime.now()))

START: 2021-10-29 10:59:15.953572
FINISH: 2021-10-29 11:11:01.521299

In [10]:
df_radiation

             0 climate_id
200001 -999.00    4010100
200002 -999.00    4010100
200003 -999.00    4010100
200004 -999.00    4010100
200005 -999.00    4010100
...        ...        ...
202009   63.17    4086001
202010   35.66    4086001
202011   20.65    4086001
202012   15.44    4086001
202013   67.32    4086001

[58422 rows x 2 columns]

In [11]:
df_radiation.reset_index(inplace = True)
df_radiation.rename(columns = { 0 : 'radiation', 'index' : 'date' }, inplace = True)
df_radiation['month'] = df_radiation['date'].str[4:]
df_radiation['year'] = df_radiation['date'].str[:4]
df_radiation.drop(columns = ['date'], inplace = True)
df_radiation

       radiation climate_id month  year
0        -999.00    4010100    01  2000
1        -999.00    4010100    02  2000
2        -999.00    4010100    03  2000
3        -999.00    4010100    04  2000
4        -999.00    4010100    05  2000
...          ...        ...   ...   ...
58417      63.17    4086001    09  2020
58418      35.66    4086001    10  2020
58419      20.65    4086001    11  2020
58420      15.44    4086001    12  2020
58421      67.32    4086001    13  2020

[58422 rows x 4 columns]

In [12]:
df['RADIATION'] = np.nan
df

,x,y,LATITUDE,LONGITUDE,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,LAST_UPDATED,PROVINCE_CODE,...,NORMAL_SNOWFALL,TOTAL_SNOWFALL,DAYS_WITH_VALID_SNOWFALL,SNOW_ON_GROUND_LAST_DAY,NORMAL_SUNSHINE,BRIGHT_SUNSHINE,DAYS_WITH_VALID_SUNSHINE,COOLING_DEGREE_DAYS,HEATING_DEGREE_DAYS,RADIATION
0,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.1,2000-01,2014-07-31 11:50:00,SK,...,NaN,25.2,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.2,2000-02,2014-07-31 11:50:00,SK,...,NaN,18.2,29.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.10,2001-10,2014-07-31 11:50:00,SK,...,NaN,1.0,31.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.11,2001-11,2014-07-31 11:50:00,SK,...,NaN,1.0,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.12,2001-12,2014-07-31 11:50:00,SK,...,NaN,0.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26424,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.10,2018-10,2018-12-06 09:47:13,SK,...,8.05,10.4,27.0,0.0,NaN,NaN,NaN,0.0,431.6,NaN
26425,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.11,2018-11,2018-12-31 14:49:21,SK,...,22.16,15.0,25.0,0.0,NaN,NaN,NaN,0.0,664.5,NaN
26426,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.12,2018-12,2019-05-16 09:47:16,SK,...,27.22,17.8,26.0,22.0,NaN,NaN,NaN,0.0,773.5,NaN
26427,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.1,2019-01,2019-05-16 09:48:50,SK,...,22.31,15.0,11.0,NaN,NaN,NaN,NaN,0.0,337.5,NaN
26428,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.3,2019-03,2019-05-16 09:48:50,SK,...,19.93,1.0,25.0,21.0,NaN,NaN,NaN,0.0,549.6,NaN

In [13]:
print('START: ' + str(datetime.now()))

df_final = pd.DataFrame()
df_subset = pd.DataFrame()
df_radiation_subset = pd.DataFrame()

for k in range(0, len(df_clid)):
    df_subset = df[df['CLIMATE_IDENTIFIER'] == df_clid.iloc[k].CLIMATE_IDENTIFIER].copy()
    df_subset.reset_index(inplace = True, drop = True)
    df_radiation_subset = df_radiation[df_radiation['climate_id'] == df_clid.iloc[k].CLIMATE_IDENTIFIER].copy()
    df_radiation_subset.reset_index(inplace = True, drop = True)
    df_radiation_subset = df_radiation_subset.astype({ 'month' : 'int32' , 'year' : 'int32' })
    for i in range (0, len(df_subset)):
        record = df_radiation_subset[(df_radiation_subset['year'] == int(df_subset.iloc[i].LOCAL_YEAR)) & \
                                     (df_radiation_subset['month'] == int(df_subset.iloc[i].LOCAL_MONTH))]
        #print(record.radiation)
        if(record.empty):
            continue
        else:
            df_subset.loc[i, ['RADIATION']] = float(record.radiation)
            
    df_final = pd.concat([df_final, df_subset], axis = 0)

print('FINISH: ' + str(datetime.now()))

START: 2021-10-29 11:11:01.832600
FINISH: 2021-10-29 11:12:16.976595

,x,y,LATITUDE,LONGITUDE,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,LAST_UPDATED,PROVINCE_CODE,...,NORMAL_SNOWFALL,TOTAL_SNOWFALL,DAYS_WITH_VALID_SNOWFALL,SNOW_ON_GROUND_LAST_DAY,NORMAL_SUNSHINE,BRIGHT_SUNSHINE,DAYS_WITH_VALID_SUNSHINE,COOLING_DEGREE_DAYS,HEATING_DEGREE_DAYS,RADIATION
0,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.1,2000-01,2014-07-31 11:50:56,SK,...,22.31,27.2,31.0,25.0,NaN,NaN,NaN,0.0,1081.3,-999.00
1,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.2,2000-02,2014-07-31 11:50:56,SK,...,16.60,1.0,29.0,11.0,NaN,NaN,NaN,0.0,806.6,-999.00
2,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.3,2000-03,2014-07-31 11:50:56,SK,...,19.93,4.4,31.0,0.0,NaN,NaN,NaN,0.0,590.8,-999.00
3,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.4,2000-04,2014-07-31 11:50:56,SK,...,13.80,22.4,30.0,0.0,NaN,NaN,NaN,0.0,425.8,-999.00
4,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.5,2000-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,0.0,237.4,-999.00
5,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.6,2000-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,3.5,142.2,-999.00
6,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.7,2000-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,67.5,41.0,-999.00
7,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.8,2000-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,32.7,63.4,-999.00
8,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.9,2000-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,0.8,202.4,-999.00
9,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.10,2000-10,2014-07-31 11:50:56,SK,...,8.05,0.0,31.0,0.0,NaN,NaN,NaN,0.0,375.0,-999.00
10,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.11,2000-11,2014-07-31 11:50:56,SK,...,22.16,55.2,30.0,24.0,NaN,NaN,NaN,0.0,808.3,-999.00
11,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2000.12,2000-12,2014-07-31 11:50:56,SK,...,27.22,36.8,31.0,37.0,NaN,NaN,NaN,0.0,1249.5,-999.00
12,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.1,2001-01,2014-07-31 11:50:56,SK,...,22.31,7.4,31.0,34.0,NaN,NaN,NaN,0.0,874.0,23.20
13,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.2,2001-02,2014-07-31 11:50:56,SK,...,16.60,20.2,28.0,46.0,NaN,NaN,NaN,0.0,1007.4,46.09
14,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.3,2001-03,2014-07-31 11:50:56,SK,...,19.93,9.0,31.0,33.0,NaN,NaN,NaN,0.0,747.7,72.84
15,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.4,2001-04,2014-07-31 11:50:56,SK,...,13.80,19.2,30.0,0.0,NaN,NaN,NaN,2.5,430.0,84.77
16,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.5,2001-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,2.3,187.2,107.85
17,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.6,2001-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,9.9,100.9,107.02
18,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.7,2001-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,61.1,20.1,112.55
19,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.8,2001-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,68.3,27.0,106.59
20,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.9,2001-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,9.7,137.3,74.55
21,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.10,2001-10,2014-07-31 11:50:56,SK,...,8.05,10.8,31.0,0.0,NaN,NaN,NaN,0.0,466.4,40.17
22,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.11,2001-11,2014-07-31 11:50:56,SK,...,22.16,18.4,30.0,3.0,NaN,NaN,NaN,0.0,571.5,19.65
23,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2001.12,2001-12,2014-07-31 11:50:56,SK,...,27.22,25.4,31.0,14.0,NaN,NaN,NaN,0.0,942.3,13.12
24,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.1,2002-01,2014-07-31 11:50:56,SK,...,22.31,22.8,31.0,19.0,NaN,NaN,NaN,0.0,1056.3,22.41
25,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.2,2002-02,2014-07-31 11:50:56,SK,...,16.60,6.8,28.0,19.0,NaN,NaN,NaN,0.0,787.4,43.87
26,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.3,2002-03,2014-07-31 11:50:56,SK,...,19.93,29.0,31.0,15.0,NaN,NaN,NaN,0.0,990.5,69.56
27,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.4,2002-04,2014-07-31 11:50:56,SK,...,13.80,25.2,30.0,0.0,NaN,NaN,NaN,0.0,544.6,87.82
28,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.5,2002-05,2014-07-31 11:50:56,SK,...,4.00,0.8,31.0,0.0,NaN,NaN,NaN,2.9,314.2,117.86
29,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.6,2002-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,48.3,67.5,108.88
30,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.7,2002-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,83.2,23.2,120.51
31,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.8,2002-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,24.6,61.8,87.65
32,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.9,2002-09,2014-07-31 11:50:56,SK,...,1.30,2.2,30.0,0.0,NaN,NaN,NaN,3.5,193.9,68.27
33,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.10,2002-10,2014-07-31 11:50:56,SK,...,8.05,13.8,31.0,5.0,NaN,NaN,NaN,0.0,607.9,38.91
34,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.11,2002-11,2014-07-31 11:50:56,SK,...,22.16,16.8,30.0,3.0,NaN,NaN,NaN,0.0,756.2,19.62
35,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2002.12,2002-12,2014-07-31 11:50:56,SK,...,27.22,79.8,31.0,47.0,NaN,NaN,NaN,0.0,862.4,14.05
36,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.1,2003-01,2014-07-31 11:50:56,SK,...,22.31,8.0,31.0,41.0,NaN,NaN,NaN,0.0,1129.4,22.54
37,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.2,2003-02,2014-07-31 11:50:56,SK,...,16.60,33.6,28.0,54.0,NaN,NaN,NaN,0.0,1049.4,42.02
38,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.3,2003-03,2014-07-31 11:50:56,SK,...,19.93,13.4,31.0,26.0,NaN,NaN,NaN,0.0,885.9,71.40
39,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.4,2003-04,2014-07-31 11:50:56,SK,...,13.80,17.0,30.0,0.0,NaN,NaN,NaN,0.0,419.5,81.57
40,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.5,2003-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,6.8,166.5,108.16
41,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.6,2003-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,28.6,68.9,112.79
42,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.7,2003-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,51.7,25.0,116.18
43,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.8,2003-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,112.3,26.3,100.02
44,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.9,2003-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,14.6,215.2,62.06
45,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.10,2003-10,2014-07-31 11:50:56,SK,...,8.05,12.6,31.0,4.0,NaN,NaN,NaN,0.0,380.7,40.55
46,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.11,2003-11,2014-07-31 11:50:56,SK,...,22.16,15.0,30.0,11.0,NaN,NaN,NaN,0.0,842.5,22.70
47,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2003.12,2003-12,2014-07-31 11:50:56,SK,...,27.22,16.8,31.0,20.0,NaN,NaN,NaN,0.0,877.7,13.76
48,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.1,2004-01,2014-07-31 11:50:56,SK,...,22.31,34.2,31.0,34.0,NaN,NaN,NaN,0.0,1230.8,20.31
49,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.2,2004-02,2014-07-31 11:50:56,SK,...,16.60,21.4,29.0,38.0,NaN,NaN,NaN,0.0,845.1,38.62
50,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.3,2004-03,2014-07-31 11:50:56,SK,...,19.93,52.4,31.0,43.0,NaN,NaN,NaN,0.0,767.2,71.71
51,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.4,2004-04,2014-07-31 11:50:56,SK,...,13.80,0.6,30.0,0.0,NaN,NaN,NaN,0.0,446.9,87.80
52,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.5,2004-05,2014-07-31 11:50:56,SK,...,4.00,4.0,31.0,0.0,NaN,NaN,NaN,0.0,342.4,92.54
53,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.6,2004-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,4.0,146.5,100.88
54,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.7,2004-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,36.1,54.1,110.04
55,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.8,2004-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,6.8,138.0,82.05
56,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.9,2004-09,2014-07-31 11:50:56,SK,...,1.30,0.4,30.0,0.0,NaN,NaN,NaN,0.0,170.0,63.12
57,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.10,2004-10,2014-07-31 11:50:56,SK,...,8.05,15.2,31.0,0.0,NaN,NaN,NaN,0.0,434.9,39.16
58,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.11,2004-11,2014-07-31 11:50:56,SK,...,22.16,9.4,30.0,3.0,NaN,NaN,NaN,0.0,614.0,24.08
59,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2004.12,2004-12,2014-07-31 11:50:56,SK,...,27.22,37.8,31.0,19.0,NaN,NaN,NaN,0.0,1045.4,14.48
60,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.1,2005-01,2014-07-31 11:50:56,SK,...,22.31,23.0,31.0,28.0,NaN,NaN,NaN,0.0,1153.9,22.41
61,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.2,2005-02,2014-07-31 11:50:56,SK,...,16.60,14.6,28.0,31.0,NaN,NaN,NaN,0.0,873.7,44.90
62,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.3,2005-03,2014-07-31 11:50:56,SK,...,19.93,16.2,31.0,24.0,NaN,NaN,NaN,0.0,786.4,73.53
63,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.4,2005-04,2014-07-31 11:50:56,SK,...,13.80,9.8,30.0,3.0,NaN,NaN,NaN,0.0,341.5,83.96
64,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.5,2005-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,0.8,252.4,100.97
65,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.6,2005-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,18.6,92.0,96.39
66,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.7,2005-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,55.1,43.3,117.86
67,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.8,2005-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,33.9,90.4,93.47
68,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.9,2005-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,8.1,170.2,68.94
69,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.10,2005-10,2014-07-31 11:50:56,SK,...,8.05,0.0,31.0,0.0,NaN,NaN,NaN,0.0,395.2,36.37
70,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.11,2005-11,2014-07-31 11:50:56,SK,...,22.16,25.0,30.0,2.0,NaN,NaN,NaN,0.0,657.1,17.10
71,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2005.12,2005-12,2014-07-31 11:50:56,SK,...,27.22,26.2,31.0,12.0,NaN,NaN,NaN,0.0,850.2,14.19
72,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.1,2006-01,2014-07-31 11:50:56,SK,...,22.31,34.2,31.0,28.0,NaN,NaN,NaN,0.0,809.1,17.52
73,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.2,2006-02,2014-07-31 11:50:56,SK,...,16.60,27.0,28.0,36.0,NaN,NaN,NaN,0.0,914.1,43.91
74,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.3,2006-03,2014-07-31 11:50:56,SK,...,19.93,23.6,31.0,34.0,NaN,NaN,NaN,0.0,769.5,70.91
75,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.4,2006-04,2014-07-31 11:50:56,SK,...,13.80,19.2,30.0,0.0,NaN,NaN,NaN,0.0,311.2,91.57
76,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.5,2006-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,5.1,208.4,94.95
77,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.6,2006-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,26.0,47.2,111.98
78,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.7,2006-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,64.1,10.8,122.05
79,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.8,2006-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,32.5,22.8,100.62
80,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.9,2006-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,4.1,183.5,66.09
81,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.10,2006-10,2014-07-31 11:50:56,SK,...,8.05,9.0,31.0,0.0,NaN,NaN,NaN,0.0,506.9,39.00
82,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.11,2006-11,2014-07-31 11:50:56,SK,...,22.16,46.2,30.0,28.0,NaN,NaN,NaN,0.0,765.9,17.10
83,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2006.12,2006-12,2014-07-31 11:50:56,SK,...,27.22,19.2,31.0,30.0,NaN,NaN,NaN,0.0,903.1,15.79
84,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.1,2007-01,2014-07-31 11:50:56,SK,...,22.31,30.8,31.0,42.0,NaN,NaN,NaN,0.0,1002.2,23.02
85,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.2,2007-02,2014-07-31 11:50:56,SK,...,16.60,31.4,28.0,54.0,NaN,NaN,NaN,0.0,1018.7,41.68
86,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.3,2007-03,2014-07-31 11:50:56,SK,...,19.93,9.0,31.0,22.0,NaN,NaN,NaN,0.0,710.1,67.61
87,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.4,2007-04,2014-07-31 11:50:56,SK,...,13.80,1.2,30.0,0.0,NaN,NaN,NaN,0.0,443.1,97.54
88,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.5,2007-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,2.8,205.5,93.18
89,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.6,2007-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,8.6,95.9,108.22
90,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.7,2007-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,97.6,16.1,117.65
91,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.8,2007-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,12.4,84.4,89.16
92,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.9,2007-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,4.6,210.6,65.48
93,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.10,2007-10,2014-07-31 11:50:56,SK,...,8.05,0.0,31.0,0.0,NaN,NaN,NaN,0.0,372.4,39.77
94,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.11,2007-11,2014-07-31 11:50:56,SK,...,22.16,22.2,30.0,10.0,NaN,NaN,NaN,0.0,734.8,17.30
95,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2007.12,2007-12,2014-07-31 11:50:56,SK,...,27.22,32.2,31.0,23.0,NaN,NaN,NaN,0.0,1045.0,14.67
96,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.1,2008-01,2014-07-31 11:50:56,SK,...,22.31,21.0,31.0,33.0,NaN,NaN,NaN,0.0,1089.3,23.13
97,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.2,2008-02,2014-07-31 11:50:56,SK,...,16.60,14.6,29.0,36.0,NaN,NaN,NaN,0.0,1038.0,42.29
98,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.3,2008-03,2014-07-31 11:50:56,SK,...,19.93,36.8,31.0,44.0,NaN,NaN,NaN,0.0,841.2,71.36
99,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.4,2008-04,2014-07-31 11:50:56,SK,...,13.80,4.8,30.0,0.0,NaN,NaN,NaN,0.0,480.7,96.61
100,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.5,2008-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,0.0,274.6,116.48
101,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.6,2008-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,11.0,91.3,111.74
102,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.7,2008-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,26.5,40.9,108.27
103,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.8,2008-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,50.4,42.4,102.17
104,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.9,2008-09,2014-07-31 11:50:56,SK,...,1.30,0.0,29.0,0.0,NaN,NaN,NaN,0.0,194.9,66.55
105,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.10,2008-10,2014-07-31 11:50:56,SK,...,8.05,2.8,31.0,0.0,NaN,NaN,NaN,0.0,381.1,40.80
106,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.11,2008-11,2014-07-31 11:50:56,SK,...,22.16,12.4,30.0,7.0,NaN,NaN,NaN,0.0,678.1,20.89
107,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2008.12,2008-12,2014-07-31 11:50:56,SK,...,27.22,48.8,31.0,27.0,NaN,NaN,NaN,0.0,1238.1,16.01
108,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.1,2009-01,2014-07-31 11:50:56,SK,...,22.31,22.4,31.0,35.0,NaN,NaN,NaN,0.0,1167.7,23.95
109,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.2,2009-02,2014-07-31 11:50:56,SK,...,16.60,32.8,28.0,47.0,NaN,NaN,NaN,0.0,933.2,43.37
110,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.3,2009-03,2014-07-31 11:50:56,SK,...,19.93,12.0,31.0,26.0,NaN,NaN,NaN,0.0,873.6,69.27
111,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.4,2009-04,2014-07-31 11:50:56,SK,...,13.80,26.8,30.0,0.0,NaN,NaN,NaN,0.0,463.7,82.53
112,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.5,2009-05,2014-07-31 11:50:56,SK,...,4.00,9.2,31.0,0.0,NaN,NaN,NaN,0.0,295.1,103.30
113,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.6,2009-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,26.6,107.6,118.45
114,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.7,2009-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,12.7,69.1,108.59
115,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.8,2009-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,10.2,70.3,84.30
116,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.9,2009-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,34.3,66.3,77.98
117,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.10,2009-10,2014-07-31 11:50:56,SK,...,8.05,6.4,31.0,0.0,NaN,NaN,NaN,0.0,484.8,28.37
118,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.11,2009-11,2014-07-31 11:50:56,SK,...,22.16,1.4,30.0,0.0,NaN,NaN,NaN,0.0,526.2,25.66
119,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2009.12,2009-12,2014-07-31 11:50:56,SK,...,27.22,32.2,31.0,18.0,NaN,NaN,NaN,0.0,1121.8,15.56
120,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.1,2010-01,2014-07-31 11:50:56,SK,...,22.31,48.4,31.0,38.0,NaN,NaN,NaN,0.0,973.5,21.58
121,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.2,2010-02,2014-07-31 11:50:56,SK,...,16.60,18.8,28.0,38.0,NaN,NaN,NaN,0.0,859.6,41.66
122,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.3,2010-03,2014-07-31 11:50:56,SK,...,19.93,5.6,31.0,0.0,NaN,NaN,NaN,0.0,602.8,68.80
123,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.4,2010-04,2014-07-31 11:50:56,SK,...,13.80,2.4,30.0,0.0,NaN,NaN,NaN,0.0,311.7,89.86
124,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.5,2010-05,2014-07-31 11:50:56,SK,...,4.00,7.6,31.0,0.0,NaN,NaN,NaN,9.3,264.3,88.09
125,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.6,2010-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,9.5,75.6,101.97
126,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.7,2010-07,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,31.7,18.5,116.29
127,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.8,2010-08,2014-07-31 11:50:56,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,32.6,61.9,84.15
128,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.9,2010-09,2014-07-31 11:50:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,0.5,215.7,66.97
129,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.10,2010-10,2014-07-31 11:50:56,SK,...,8.05,26.4,31.0,12.0,NaN,NaN,NaN,0.0,338.6,47.23
130,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.11,2010-11,2014-07-31 11:50:56,SK,...,22.16,52.4,30.0,22.0,NaN,NaN,NaN,0.0,751.6,19.38
131,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2010.12,2010-12,2014-07-31 11:50:56,SK,...,27.22,43.8,31.0,36.0,NaN,NaN,NaN,0.0,1039.6,16.09
132,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2011.1,2011-01,2014-07-31 11:50:56,SK,...,22.31,34.2,31.0,50.0,NaN,NaN,NaN,0.0,1127.2,21.96
133,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2011.2,2011-02,2014-07-31 11:50:56,SK,...,16.60,28.6,28.0,59.0,NaN,NaN,NaN,0.0,940.5,43.59
134,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2011.3,2011-03,2014-07-31 11:50:56,SK,...,19.93,30.2,31.0,63.0,NaN,NaN,NaN,0.0,901.1,71.97

In [14]:
df_final

,x,y,LATITUDE,LONGITUDE,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,LAST_UPDATED,PROVINCE_CODE,...,NORMAL_SNOWFALL,TOTAL_SNOWFALL,DAYS_WITH_VALID_SNOWFALL,SNOW_ON_GROUND_LAST_DAY,NORMAL_SUNSHINE,BRIGHT_SUNSHINE,DAYS_WITH_VALID_SUNSHINE,COOLING_DEGREE_DAYS,HEATING_DEGREE_DAYS,RADIATION
0,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.1,2000-01,2014-07-31 11:50:00,SK,...,NaN,25.2,31.0,NaN,NaN,NaN,NaN,NaN,NaN,-999.00
1,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2000.2,2000-02,2014-07-31 11:50:00,SK,...,NaN,18.2,29.0,0.0,NaN,NaN,NaN,NaN,NaN,-999.00
2,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.10,2001-10,2014-07-31 11:50:00,SK,...,NaN,1.0,31.0,0.0,NaN,NaN,NaN,NaN,NaN,44.87
3,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.11,2001-11,2014-07-31 11:50:00,SK,...,NaN,1.0,30.0,0.0,NaN,NaN,NaN,NaN,NaN,25.20
4,-101.8,49.450000,49.450,-101.8,ALIDA,4010100,2840.2001.12,2001-12,2014-07-31 11:50:00,SK,...,NaN,0.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,19.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.10,2018-10,2018-12-06 09:47:13,SK,...,8.05,10.4,27.0,0.0,NaN,NaN,NaN,0.0,431.6,34.60
216,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.11,2018-11,2018-12-31 14:49:21,SK,...,22.16,15.0,25.0,0.0,NaN,NaN,NaN,0.0,664.5,17.73
217,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.12,2018-12,2019-05-16 09:47:16,SK,...,27.22,17.8,26.0,22.0,NaN,NaN,NaN,0.0,773.5,16.43
218,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.1,2019-01,2019-05-16 09:48:50,SK,...,22.31,15.0,11.0,NaN,NaN,NaN,NaN,0.0,337.5,23.01
219,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.3,2019-03,2019-05-16 09:48:50,SK,...,19.93,1.0,25.0,21.0,NaN,NaN,NaN,0.0,549.6,77.33

#### DO NOT USE

print('START: ' + str(datetime.now()))

df_final = pd.DataFrame()
df_subset = pd.DataFrame()

for k in range(0, len(df_clid)):
    df_subset = df[df['CLIMATE_IDENTIFIER'] == df_clid.iloc[k].CLIMATE_IDENTIFIER]
    df_subset.reset_index(inplace = True, drop = True)
    df_radiation_subset = df_radiation[df_radiation['climate_id'] == df_clid.iloc[k].CLIMATE_IDENTIFIER]
    df_radiation_subset.reset_index(inplace = True, drop = True)
    #print(df_subset)
    for i in range (0, len(df_subset)):
        for j in range (0, len(df_radiation_subset)):
            if ((df_subset.iloc[i].CLIMATE_IDENTIFIER == df_radiation_subset.iloc[j].climate_id) \
                & (int(df_subset.iloc[i].LOCAL_YEAR) == int(df_radiation_subset.iloc[j].year)) \
                & (int(df_subset.iloc[i].LOCAL_MONTH) == int(df_radiation_subset.iloc[j].month))):
                #print(f'found record {i} at {j}')
                df_subset.loc[i:i, ['RADIATION']] = df_radiation_subset.iloc[j].radiation
                break
    df_final = pd.concat([df_final, df_subset], axis = 0)

print('FINISH: ' + str(datetime.now()))

In [15]:
df_final.tail(50)

,x,y,LATITUDE,LONGITUDE,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,LAST_UPDATED,PROVINCE_CODE,...,NORMAL_SNOWFALL,TOTAL_SNOWFALL,DAYS_WITH_VALID_SNOWFALL,SNOW_ON_GROUND_LAST_DAY,NORMAL_SUNSHINE,BRIGHT_SUNSHINE,DAYS_WITH_VALID_SUNSHINE,COOLING_DEGREE_DAYS,HEATING_DEGREE_DAYS,RADIATION
170,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.3,2014-03,2014-07-31 11:50:56,SK,...,19.93,19.6,31.0,38.0,NaN,NaN,NaN,0.0,935.3,73.71
171,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.4,2014-04,2014-07-31 11:50:56,SK,...,13.80,27.0,30.0,0.0,NaN,NaN,NaN,0.0,542.1,86.27
172,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.5,2014-05,2014-07-31 11:50:56,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,15.9,236.8,102.02
173,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.6,2014-06,2014-07-31 11:50:56,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,4.6,99.3,91.45
174,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.7,2014-07,2014-08-02 09:51:33,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,31.1,32.9,117.93
175,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.8,2014-08,2014-09-30 14:57:11,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,48.0,40.4,91.97
176,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.9,2014-09,2014-10-02 09:53:56,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,17.3,185.7,66.38
177,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.10,2014-10,2014-11-08 21:23:56,SK,...,8.05,2.8,31.0,0.0,NaN,NaN,NaN,0.0,382.4,40.76
178,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.11,2014-11,2014-12-02 10:09:51,SK,...,22.16,28.4,30.0,18.0,NaN,NaN,NaN,0.0,854.8,20.86
179,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2014.12,2014-12,2015-01-02 09:51:35,SK,...,27.22,15.8,31.0,19.0,NaN,NaN,NaN,0.0,897.3,14.42
180,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.1,2015-01,2015-02-02 10:01:06,SK,...,22.31,22.2,31.0,29.0,NaN,NaN,NaN,0.0,1006.4,22.09
181,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.2,2015-02,2015-03-06 09:53:28,SK,...,16.60,20.0,28.0,38.0,NaN,NaN,NaN,0.0,1057.3,44.65
182,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.3,2015-03,2015-04-02 10:06:48,SK,...,19.93,18.2,31.0,8.0,NaN,NaN,NaN,0.0,694.0,67.48
183,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.4,2015-04,2015-05-03 05:39:14,SK,...,13.80,12.4,30.0,0.0,NaN,NaN,NaN,0.0,396.4,91.26
184,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.5,2015-05,2015-06-04 09:48:13,SK,...,4.00,0.0,31.0,0.0,NaN,NaN,NaN,2.8,228.0,112.16
185,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.6,2015-06,2015-07-02 09:49:27,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,22.2,51.5,115.77
186,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.7,2015-07,2015-08-06 09:51:14,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,65.9,18.6,107.27
187,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.8,2015-08,2015-09-02 09:48:37,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,41.6,45.5,87.11
188,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.9,2015-09,2015-10-02 09:48:22,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,8.6,160.3,64.78
189,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.10,2015-10,2015-11-02 09:53:29,SK,...,8.05,7.0,31.0,0.0,NaN,NaN,NaN,0.0,347.4,42.04
190,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.11,2015-11,2015-12-02 09:47:37,SK,...,22.16,29.8,30.0,11.0,NaN,NaN,NaN,0.0,619.5,18.89
191,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2015.12,2015-12,2016-01-02 09:46:36,SK,...,27.22,15.8,31.0,15.0,NaN,NaN,NaN,0.0,844.7,14.72
192,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.1,2016-01,2016-02-04 09:47:01,SK,...,22.31,21.6,31.0,23.0,NaN,NaN,NaN,0.0,952.0,21.78
193,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.2,2016-02,2016-03-02 09:45:59,SK,...,16.60,32.8,29.0,38.0,NaN,NaN,NaN,0.0,820.7,39.05
194,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.3,2016-03,2016-04-02 09:53:35,SK,...,19.93,36.2,31.0,15.0,NaN,NaN,NaN,0.0,667.8,67.87
195,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.4,2016-04,2016-05-02 09:48:12,SK,...,13.80,35.0,30.0,0.0,NaN,NaN,NaN,0.0,482.3,86.14
196,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.5,2016-05,2016-06-02 09:48:40,SK,...,4.00,1.6,31.0,0.0,NaN,NaN,NaN,15.8,131.9,103.91
197,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.6,2016-06,2016-07-02 09:49:06,SK,...,NaN,0.0,30.0,0.0,NaN,NaN,NaN,19.1,40.6,121.70
198,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.7,2016-07,2016-08-03 09:50:11,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,39.6,17.4,108.84
199,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.8,2016-08,2016-09-02 09:51:48,SK,...,NaN,0.0,31.0,0.0,NaN,NaN,NaN,13.0,53.4,89.16
200,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.9,2016-09,2016-10-02 09:49:53,SK,...,1.30,0.0,30.0,0.0,NaN,NaN,NaN,8.1,175.4,66.79
201,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.10,2016-10,2016-11-04 09:49:46,SK,...,8.05,13.8,31.0,0.0,NaN,NaN,NaN,0.0,450.9,27.47
202,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.11,2016-11,2016-12-02 10:01:50,SK,...,22.16,10.0,30.0,6.0,NaN,NaN,NaN,0.0,482.2,20.54
203,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2016.12,2016-12,2017-01-02 09:48:14,SK,...,27.22,17.8,31.0,14.0,NaN,NaN,NaN,0.0,1008.4,13.93
204,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.1,2017-01,2017-02-02 09:49:58,SK,...,22.31,26.8,31.0,24.0,NaN,NaN,NaN,0.0,965.6,22.80
205,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.2,2017-02,2017-03-02 09:50:19,SK,...,16.60,5.2,28.0,19.0,NaN,NaN,NaN,0.0,801.2,43.28
206,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.3,2017-03,2017-04-02 10:06:28,SK,...,19.93,44.2,31.0,14.0,NaN,NaN,NaN,0.0,798.6,68.70
207,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.4,2017-04,2017-05-19 09:51:55,SK,...,13.80,6.6,30.0,0.0,NaN,NaN,NaN,0.0,417.3,92.42
208,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.5,2017-05,2017-06-30 14:50:35,SK,...,4.00,0.0,5.0,0.0,NaN,NaN,NaN,0.0,15.9,106.77
209,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.6,2017-06,2017-07-31 14:49:08,SK,...,NaN,0.0,26.0,0.0,NaN,NaN,NaN,21.5,76.9,107.68
210,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.7,2017-07,2017-08-31 14:51:00,SK,...,NaN,0.0,7.0,NaN,NaN,NaN,NaN,7.8,6.6,125.14
211,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.8,2017-08,2017-09-30 14:53:37,SK,...,NaN,0.0,12.0,0.0,NaN,NaN,NaN,13.7,15.0,101.94
212,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.9,2017-09,2017-10-31 14:49:15,SK,...,1.30,0.0,27.0,0.0,NaN,NaN,NaN,9.0,15.3,66.58
213,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2017.10,2017-10,2017-11-30 14:49:40,SK,...,8.05,0.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,40.07
214,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.9,2018-09,2018-10-31 16:23:46,SK,...,1.30,1.8,20.0,0.0,NaN,NaN,NaN,0.0,238.4,55.79
215,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.10,2018-10,2018-12-06 09:47:13,SK,...,8.05,10.4,27.0,0.0,NaN,NaN,NaN,0.0,431.6,34.60
216,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.11,2018-11,2018-12-31 14:49:21,SK,...,22.16,15.0,25.0,0.0,NaN,NaN,NaN,0.0,664.5,17.73
217,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2018.12,2018-12,2019-05-16 09:47:16,SK,...,27.22,17.8,26.0,22.0,NaN,NaN,NaN,0.0,773.5,16.43
218,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.1,2019-01,2019-05-16 09:48:50,SK,...,22.31,15.0,11.0,NaN,NaN,NaN,NaN,0.0,337.5,23.01
219,-101.9,51.733333,51.733,-101.9,PELLY 2,4086001,3449.2019.3,2019-03,2019-05-16 09:48:50,SK,...,19.93,1.0,25.0,21.0,NaN,NaN,NaN,0.0,549.6,77.33

In [16]:
df_final.reset_index(inplace = True, drop = True)
df = df_final.copy()

In [17]:
connection = mysql.connector.connect(user='root', password='your_password', host='127.0.0.1', database='field_crops')
cursor = connection.cursor()

add_observation = ("INSERT INTO observation "
                   "(climate_ID, year, month, mean_temperature, maximum_temperature, minimum_temperature, precipitation, solar_radiation) "
                   "VALUES (%s, %s, %s, %s, %s, %s, %s, %s)")
               
                   
#a = 1

for i in range(0, len(df)):

    record = df.iloc[i]
    
    climate_ID = str(record.CLIMATE_IDENTIFIER)
    if ((len(climate_ID) != 7) \
        #British Columbia
        | (climate_ID == '1018633') | (climate_ID == '1107710') | (climate_ID == '1135126') \
        #Alberta
        | (climate_ID == '3026264') | (climate_ID == '306E304') | (climate_ID == '30705E9') \
        #Saskatchewan
        | (climate_ID == '4038116') | (climate_ID == '4038740') \
        #Manitoba
        | (climate_ID == '5020881')| (climate_ID == '5020882') | (climate_ID == '5022065') \
        | (climate_ID == '50420E5') \
        #Ontario
        | (climate_ID == '6020559') | (climate_ID == '611E001') | (climate_ID == '6134F10') \
        | (climate_ID == '6135657') | (climate_ID == '6136699') | (climate_ID == '6137937') \
        | (climate_ID == '613KLLM') | (climate_ID == '615S002') \
        #Quebec
        | (climate_ID == '7018560') \
        #New Brunswick
        #Nova Scotia
        #Newfoundland Labrador
        #Prince Edward Island
       ):
        continue
        #print(climate_ID)
        #climate_ID = 'AAAAAA' + str(a)
        #a += 1
    
    year = int(record.LOCAL_YEAR)
    month = int(record.LOCAL_MONTH)
    mean_temperature = float(record.MEAN_TEMPERATURE)
    maximum_temperature = float(record.MAX_TEMPERATURE)
    minimum_temperature = float(record.MIN_TEMPERATURE)
    precipitation = float(record.TOTAL_PRECIPITATION)
    solar_radiation = float(record.RADIATION)
   
    if(math.isnan(mean_temperature)):
        mean_temperature = None
    if(math.isnan(maximum_temperature)):
        maximum_temperature = None
    if(math.isnan(minimum_temperature)):
        minimum_temperature = None
    if(math.isnan(precipitation)):
        precipitation = None
    elif(precipitation < 0):
        precipitation = 0
    if(math.isnan(solar_radiation)):
        solar_radiation = None
    elif(solar_radiation < 0):
        solar_radiation = None
        
    data_observation = (climate_ID, year, month, mean_temperature, maximum_temperature, minimum_temperature, \
                        precipitation, solar_radiation)
    
    cursor.execute(add_observation, data_observation)
    connection.commit()


cursor.close()
connection.close()

In [18]:
# conda install requests

# import requests

In [19]:
# response = requests.get('https://power.larc.nasa.gov/api/temporal/monthly/point?parameters=ALLSKY_SFC_PAR_TOT&community=AG&longitude=-123.3920&latitude=48.5730&format=JSON&start=2010&end=2020')

In [20]:
# response.json()